### ISSUE TITLE
Update for Taurine (1.0)

### ISSUE THREAD

**Issue by kyle-import** [XsF1re/vnodebypass#15]
Taurine has now been released alongside "libKernRW", which is Coolstar's kernel r/w API for iOS 14.0+. This API can be found on the Odyssey's repository. Vnodebypass does not work with this API and needs to be updated in-order for it to work with devices running Taurine.

**Comment by aspenluxxxy** [comment]
See: https://github.com/XsF1re/vnodebypass/issues/15

**Comment by aspenluxxxy** [comment]
This can be closed now, due to https://github.com/XsF1re/vnodebypass/commit/870b21fd3566736cca285355b4faf7f289baa4d5
