### ISSUE TITLE
After updat to 0.2.3 Taurine vnodebypass icon doesn’t appear 

### ISSUE THREAD

**Issue by AlawiYNWA** [XsF1re/vnodebypass#17]
Hi 
Icon not showing On My SB 
any Terminal Way to activate it
thanks

**Comment by clemone543** [comment]
Tried to restart uicache?

**Comment by AlawiYNWA** [comment]
yes i do 
and reboot & rejailbreak 
still not Solved

**Comment by AlawiYNWA** [comment]
Solved 
I delete some tweaks preferences via Icleaner pro
Its work now 
thanks for helping
