### ISSUE TITLE
not working on taurine 1.0.2

### ISSUE THREAD

**Issue by JakoDel** [XsF1re/vnodebypass#20]
title. vnodebypass just says "failed" when trying to enable it. I'd like to attach some logs, but I don't really know how to get em lol

**Comment by jeasimon** [comment]
I have the same issue (iPhone X, 14.3, on Taurine 1.0.2)

**Comment by JakoDel** [comment]
> I have the same issue (iPhone X, 14.3, on Taurine 1.0.2)

fixed by installing kernw or something like that you can find it on sileo

**Comment by jeasimon** [comment]
Yep working now, had to install libkernrw
