### ISSUE TITLE
iphone13,3 ios 14.3 enabling vnodebypass

### ISSUE THREAD

**Issue by benqut** [XsF1re/vnodebypass#9]
when i enable vnodebypass (through the app or through powerselector) it lets pogo launch but then when i relaunch cydia it does not launch, unc0ver still says im jailbroken but cannot use any installed apps/tweaks, i need to reboot and re jailbreak the device. Any way i can log this? first ios device since my iphone 3gs

edit:
-----using vnodebypass 0.2.2-----
okay maybe i was using 0.2.1 but i used terminal to activate it this time (definitely using 0.2.2 and i used powerselector again to disable it after using term to enable it and it crashed cydia again >:   )
unc0ver 6.1.0
________________________________________________
edit:
okay need to enable it term and in the powerselector, then if it screws up and i can still access term i can disable in term and have to disable in powerselector to stop it from crashing cydia
________________________________________________
edit: found some logs seems to have something to do with that segmentation fault 11 as someone else mentioned in another issue [https://github.com/XsF1re/vnodebypass/issues/6](url)

**Comment by benqut** [comment]
[ReportCrash-2021-03-06-163235.txt](https://github.com/XsF1re/vnodebypass/files/6094859/ReportCrash-2021-03-06-163235.txt)
[ReportCrash-2021-03-06-163225.txt](https://github.com/XsF1re/vnodebypass/files/6094860/ReportCrash-2021-03-06-163225.txt)
[ReportCrash-2021-03-06-163151.txt](https://github.com/XsF1re/vnodebypass/files/6094861/ReportCrash-2021-03-06-163151.txt)
[ReportCrash-2021-03-06-163109.txt](https://github.com/XsF1re/vnodebypass/files/6094862/ReportCrash-2021-03-06-163109.txt)
[pokemongo-2021-03-06-163359.txt](https://github.com/XsF1re/vnodebypass/files/6094863/pokemongo-2021-03-06-163359.txt)
[pokemongo-2021-03-06-163356.txt](https://github.com/XsF1re/vnodebypass/files/6094865/pokemongo-2021-03-06-163356.txt)
[pokemongo-2021-03-06-163355.txt](https://github.com/XsF1re/vnodebypass/files/6094866/pokemongo-2021-03-06-163355.txt)
[backboardd.wakeups_resource-2021-03-06-163354.txt](https://github.com/XsF1re/vnodebypass/files/6094867/backboardd.wakeups_resource-2021-03-06-163354.txt)
[stacks+pokemongo-2021-03-06-163250.txt](https://github.com/XsF1re/vnodebypass/files/6094868/stacks%2Bpokemongo-2021-03-06-163250.txt)

**Comment by diegoorosa** [comment]
I’m always getting problem using vnodebypass.
Like your, I enable using PowerSelector, open my bank app, everything is ok.
When I finished using, I disable using PowerSelector again. But my device gets mess up. Cydia crashes too, other apps crash, if open PowerSelector I runs wierd. I had to reboot and jailbreak again to back to normal. What am I doing wrong?

**Comment by benqut** [comment]
> I’m always getting problem using vnodebypass.
> Like your, I enable using PowerSelector, open my bank app, everything is ok.
> When I finished using, I disable using PowerSelector again. But my device gets mess up. Cydia crashes too, other apps crash, if open PowerSelector I runs wierd. I had to reboot and jailbreak again to back to normal. What am I doing wrong?

you can disable it in the powersel app, and disable it in terminal 
su
vnodebypass -r
(-r to restore and -h to enable)
